import { z } from "zod";



export const projectBriefSchema = z.object({
    format: z.string().min(1).describe("The format of the content (e.g., 'screenplay', 'short film', 'series episode')"),
    genre: z.string().min(1).describe("The primary genre of the story (e.g., 'drama', 'thriller', 'comedy')"),
    durationMin: z.number().min(1).describe("The estimated runtime in minutes"),
    tone: z.array(z.string()).min(1).describe("The tonal qualities of the story (e.g., ['dark', 'suspenseful', 'emotional'])"),
    audience: z.string().min(1).describe("The target audience for the content (e.g., 'general', 'mature', 'young adult')"),
    storyIdea: z.string().min(1).describe("The initial idea or premise that will be developed into a full script"),
});

export const narrativeArcSchema = z.object({
    title: z.string().min(1).describe("The working title of the concept"),
    logline: z.string().min(1).describe("One sentence that captures the essence of the story"),
    synopsis: z.string().min(1).describe("2-3 paragraph narrative arc description"),
    genre: z.array(z.string()).min(1).describe("The genres that apply to this concept (e.g., ['drama', 'thriller'])"),
    tone: z.array(z.string()).min(1).describe("The tonal qualities (e.g., ['dark', 'suspenseful'])"),
    themes: z.array(z.string()).describe("The thematic elements explored in the story (e.g., ['redemption', 'family'])"),
    source: z.enum(["agent", "user"]).describe("Whether this concept was generated by the AI agent or provided by the user. Always 'agent' for AI-generated concepts."),
    isSelected: z.boolean().describe("Whether this concept has been selected by the user to develop further. Always false for newly generated concepts."),
  });

export const narrativeArcListSchema = z.array(narrativeArcSchema);

export const sceneOutlineSchema = z.object({
    scene_number: z.number().describe("Sequential scene number within the script (e.g., 1, 2, 3)"),
    slugline: z.string().min(1).describe("Scene heading in standard format (e.g., 'INT. COFFEE SHOP - DAY')"),
    characters_present: z.array(z.string()).describe("Names of characters appearing in this scene"),
    scene_goal: z.string().describe("What this scene needs to accomplish narratively"),
    action_summary: z.string().describe("2-3 sentence summary of what happens in the scene. Include the key conflict or obstacle, the major emotional turn, and the specific new information, decision, or consequence that propels the next scene. Keep it very concise and to the point."),
});

const beatSchema = z.object({
    beat_name: z.string().min(1).describe("Name of the story beat (e.g., 'Opening Image', 'Inciting Incident', 'Midpoint')"),
    summary: z.string().min(1).describe("A very concise description of what happens in this beat (1-2 sentences)"),
    scenes: z.array(sceneOutlineSchema).describe("Scenes that comprise this beat"),
});

export const scriptOutlineSchema = z.object({
    beats: z.array(beatSchema).describe("Story beats that structure the script, each containing related scenes"),
});

export const synopsisSchema = z.object({
    title: z.string().min(1).describe("The title of the synopsis"),
    text: z.string().min(1).describe("The complete synopsis as prose, breaking story into beginning/middle/end structure with protagonist arc, central conflict, and key turning points"),
});


export const CharacterSchema = z.object({
    name: z.string().min(1).describe("The character's full name (e.g., 'Sarah Chen')"),
    role: z.enum(["protagonist", "antagonist", "supporting", "minor"]).describe("The character's role in the story"),
    age: z.number().min(1).describe("The character's age"),
    occupation: z.string().min(1).describe("The character's job or primary role in life (e.g., 'Detective')"),
    physicalDescription: z.string().min(1).describe("Visual description of the character's appearance"),
    personalityTraits: z.array(z.string()).min(1).describe("Key personality traits (e.g., ['determined', 'secretive', 'compassionate'])"),
    backstory: z.string().min(1).describe("Relevant history that shapes who the character is"),
    motivation: z.string().min(1).describe("What drives the character - their primary goal or desire"),
    flaw: z.string().min(1).describe("The character's key weakness or fatal flaw"),
    voice: z.string().min(1).describe("How the character speaks - speech patterns, vocabulary level, verbal tics, and sample dialogue"),
});

export const LocationSchema = z.object({
    name: z.string().min(1).describe("The name of the location (e.g., 'The Precinct')"),
    description: z.string().min(1).describe("Detailed visual description of the location"),
});

export const PropSchema = z.object({
    name: z.string().min(1).describe("The name of the prop (e.g., 'Sarah's Badge')"),
    description: z.string().min(1).describe("Description of the prop and its narrative significance (e.g., 'Worn, scratched detective badge - Symbol of her identity crisis')"),
});

const keyLocationOutlineSchema = z.object({
    name: z.string().min(1).describe("Name of the location (e.g., 'The Warehouse', 'City Hall')"),
    description: z.string().describe("Physical and atmospheric description of the place"),
    significance: z.string().describe("Why this location matters to the story or characters. Keep it very concise (1-2 sentences)."),
});

const keyCharacterOutlineSchema = z.object({
    name: z.string().min(1).describe("Character's full name or primary alias"),
    role: z.enum(["protagonist", "antagonist", "supporting"]).describe("Narrative function in the story"),
    age: z.number().min(1).describe("Character's age in years"),
    goal: z.string().describe("What the character wants or is driving toward in the story. Keep it very concise (1-2 sentences)."),
});

export const storyBibleSchema = z.object({
    world: z.object({
        setting: z.string().min(1).describe("The primary location or world where the story unfolds (e.g., 'Chicago', 'Small coastal town')"),
        timePeriod: z.string().min(1).describe("When the story takes place (e.g., 'Present day', '1920s', 'Near future')"),
        worldRules: z.string().describe("A very concise rules or logic that govern the world (magic, tech, social norms).(2-3 sentences)"),
        socialContext: z.string().describe("A very concise of the social structure, power dynamics, and cultural context.(2-3 sentences)"),
    }),
    conflictEngine: z.object({
        centralConflict: z.string().describe("The main opposing forces or dilemma driving the plot"),
        stakes: z.string().describe("What can be won or lost; consequences of failure"),
        antagonisticForce: z.string().describe("Who or what opposes the protagonist"),
        timePressure: z.string().describe("Deadlines, ticking clocks, or urgency"),
        mainDramaticQuestion: z.string().describe("The story question the audience wants answered (e.g., 'Will they escape?')"),
    }),
    keyLocations: z.array(keyLocationOutlineSchema).describe("Key locations with name, description, and significance"),
    keyCharacters: z.array(keyCharacterOutlineSchema).describe("Key characters with role, age, and goal"),
    toneAndStyle: z.object({
        visualStyle: z.string().describe("Look and feel (e.g., noir, documentary, high contrast)"),
        dialogueStyle: z.string().describe("How characters speak (e.g., naturalistic, stylized, sparse)"),
        pacing: z.string().describe("Rhythm of the story (e.g., slow burn, propulsive, episodic)"),
    }),
    continuityRules: z.object({
        factsToConsistent: z.string().describe("A very concise established facts that must stay consistent"),
        characterBehaviorRules: z.string().describe("A very concise how characters should act and react consistently"),
        thingsToAvoid: z.string().describe("A very concise contradictions or mistakes to avoid"),
    }),
}).describe("The story bible is a comprehensive outline of the story, including the world, conflict engine, key locations, key characters, tone and style, and continuity rules. Keep each section very concise (1-3 sentences) and to the point.");

// ProseMirror/Tiptap Mark schema (inline formatting)
export const proseMarkSchema = z.object({
    type: z.string().min(1),
    attrs: z.record(z.string(), z.any()).optional(),
});

// Type definitions for recursive schema
type ProseNodeType = {
    type: string;
    attrs?: Record<string, unknown>;
    content?: ProseNodeType[];
    text?: string;
    marks?: { type: string; attrs?: Record<string, unknown> }[];
};

// ProseMirror/Tiptap Node schema (recursive)
export const proseNodeSchema: z.ZodType<ProseNodeType> = z.object({
    type: z.string().min(1),
    attrs: z.record(z.string(), z.any()).optional(),
    content: z.lazy(() => z.array(proseNodeSchema)).optional(),
    text: z.string().optional(),
    marks: z.array(proseMarkSchema).optional(),
}) as z.ZodType<ProseNodeType>;

// ProseMirror/Tiptap Document schema (root)
export const proseDocumentSchema = z.object({
    type: z.literal("doc"),
    content: z.array(proseNodeSchema),
});

export const sceneContentBlockSchema = z.discriminatedUnion("type", [
    z.object({
        type: z.literal("slugline"),
        text: z.string().min(1).describe("Scene heading in screenplay format, e.g. 'INT. APARTMENT - NIGHT'"),
        locationId: z.string().optional().describe("Optional linked location entity id"),
    }),
    z.object({
        type: z.literal("action"),
        text: z.string().min(1).describe("Action line describing what is seen or happens on screen"),
    }),
    z.object({
        type: z.literal("dialogue"),
        text: z.string().min(1).describe("Spoken dialogue text"),
        character: z.string().min(1).describe("Character name speaking the dialogue"),
        parenthetical: z.string().min(1).optional().describe("Optional parenthetical performance direction"),
    }),
    z.object({
        type: z.literal("transition"),
        text: z.string().min(1).describe("Screenplay transition text, e.g. 'CUT TO:'"),
    }),
]).describe("Single screenplay scene block");

export const sceneContentSchema = z
    .array(sceneContentBlockSchema)
    .min(1)
    .describe("An ordered array of screenplay scene blocks");



// Type exports
export type ProjectBrief = z.infer<typeof projectBriefSchema>;
export type NarrativeArc = z.infer<typeof narrativeArcSchema>;
export type NarrativeArcList = z.infer<typeof narrativeArcListSchema>;
export type Outline = z.infer<typeof scriptOutlineSchema>;
export type SceneOutline = z.infer<typeof sceneOutlineSchema>;
export type Synopsis = z.infer<typeof synopsisSchema>;
export type StoryBible = z.infer<typeof storyBibleSchema>;
export type ProseMark = z.infer<typeof proseMarkSchema>;
export type ProseNode = ProseNodeType;
export type ProseDocument = z.infer<typeof proseDocumentSchema>;
export type SceneContentBlock = z.infer<typeof sceneContentBlockSchema>;
export type SceneContentSchema = z.infer<typeof sceneContentSchema>;
export type Character = z.infer<typeof CharacterSchema>;
export type Location = z.infer<typeof LocationSchema>;
export type Prop = z.infer<typeof PropSchema>;
export type EntityObject = Character | Location | Prop;