import { z } from "zod";



export const projectBriefSchema = z.object({
    format: z.string().min(1).describe("The format of the content (e.g., 'screenplay', 'short film', 'series episode')"),
    genre: z.string().min(1).describe("The primary genre of the story (e.g., 'drama', 'thriller', 'comedy')"),
    durationMin: z.number().min(1).describe("The estimated runtime in minutes"),
    tone: z.array(z.string()).min(1).describe("The tonal qualities of the story (e.g., ['dark', 'suspenseful', 'emotional'])"),
    audience: z.string().min(1).describe("The target audience for the content (e.g., 'general', 'mature', 'young adult')"),
    storyIdea: z.string().min(1).describe("The initial idea or premise that will be developed into a full script"),
});

export const narrativeArcSchema = z.object({
    title: z.string().min(1).describe("The working title of the concept"),
    logline: z.string().min(1).describe("One sentence that captures the essence of the story"),
    synopsis: z.string().min(1).describe("2-3 paragraph narrative arc description"),
    genre: z.array(z.string()).min(1).describe("The genres that apply to this concept (e.g., ['drama', 'thriller'])"),
    tone: z.array(z.string()).min(1).describe("The tonal qualities (e.g., ['dark', 'suspenseful'])"),
    themes: z.array(z.string()).describe("The thematic elements explored in the story (e.g., ['redemption', 'family'])"),
    source: z.enum(["agent", "user"]).describe("Whether this concept was generated by the AI agent or provided by the user. Always 'agent' for AI-generated concepts."),
    isSelected: z.boolean().describe("Whether this concept has been selected by the user to develop further. Always false for newly generated concepts."),
  });

export const narrativeArcListSchema = z.array(narrativeArcSchema);


export const outlineSchema = z.object({
    actId: z.string().min(1).describe("The unique identifier for the act (e.g., 'act_1', 'act_2')"),
    beat: z.object({
        beatId: z.string().min(1).describe("The unique identifier for the beat (e.g., 'beat_opening_image')"),
        title: z.string().min(1).describe("The name of the beat (e.g., 'Opening Image', 'Inciting Incident', 'Midpoint')"),
        summary: z.string().min(1).describe("A description of what happens in this beat"),
        goals: z.array(z.string()).min(1).describe("What this beat accomplishes narratively"),
        turningPoints: z.array(z.string()).min(1).describe("Key moments that shift the story direction within this beat"),
    }).describe("The dramatic beat that this section of the outline represents"),
    scenes: z.array(z.object({
        sceneId: z.string().min(1).describe("The unique identifier for the scene (e.g., 'scene_001')"),
        slugline: z.string().min(1).describe("The scene heading in standard format (e.g., 'INT. COFFEE SHOP - DAY')"),
        summary: z.string().min(1).describe("Brief description of what happens in the scene and its purpose"),
    })).describe("The list of scenes that make up this beat"),
});

export const outlineListSchema = z.array(outlineSchema);

export const synopsisSchema = z.object({
    title: z.string().min(1).describe("The title of the synopsis"),
    text: z.string().min(1).describe("The complete synopsis as prose, breaking story into beginning/middle/end structure with protagonist arc, central conflict, and key turning points"),
});


export const CharacterSchema = z.object({
    id: z.string().min(1).describe("The unique identifier for the character (e.g., 'char_sarah_chen')"),
    name: z.string().min(1).describe("The character's full name (e.g., 'Sarah Chen')"),
    role: z.enum(["protagonist", "antagonist", "supporting", "minor"]).describe("The character's role in the story"),
    age: z.number().min(1).describe("The character's age"),
    occupation: z.string().min(1).describe("The character's job or primary role in life (e.g., 'Detective')"),
    physicalDescription: z.string().min(1).describe("Visual description of the character's appearance"),
    personalityTraits: z.array(z.string()).min(1).describe("Key personality traits (e.g., ['determined', 'secretive', 'compassionate'])"),
    backstory: z.string().min(1).describe("Relevant history that shapes who the character is"),
    motivation: z.string().min(1).describe("What drives the character - their primary goal or desire"),
    flaw: z.string().min(1).describe("The character's key weakness or fatal flaw"),
    voice: z.string().min(1).describe("How the character speaks - speech patterns, vocabulary level, verbal tics, and sample dialogue"),
});

export const LocationSchema = z.object({
    id: z.string().min(1).describe("The unique identifier for the location (e.g., 'loc_precinct')"),
    name: z.string().min(1).describe("The name of the location (e.g., 'The Precinct')"),
    description: z.string().min(1).describe("Detailed visual description of the location"),
    atmosphere: z.string().min(1).describe("The mood and feel of the location (e.g., 'Fluorescent-lit, coffee-stained chaos')"),
});

export const PropSchema = z.object({
    id: z.string().min(1).describe("The unique identifier for the prop (e.g., 'prop_sarahs_badge')"),
    name: z.string().min(1).describe("The name of the prop (e.g., 'Sarah's Badge')"),
    description: z.string().min(1).describe("Description of the prop and its narrative significance (e.g., 'Worn, scratched detective badge - Symbol of her identity crisis')"),
});

export const storyBibleSchema = z.object({
    timePeriod: z.string().min(1).describe("When the story takes place (e.g., 'Present day', '1920s', 'Near future')"),
    setting: z.string().min(1).describe("The primary location or world where the story unfolds (e.g., 'Chicago', 'Small coastal town')"),
    characters: z.array(CharacterSchema).describe("All characters in the story with their details, relationships, and arcs"),
    locations: z.array(LocationSchema).describe("All significant locations that appear in the story"),
    props: z.array(PropSchema).describe("Important props that have narrative significance"),
});

// ProseMirror/Tiptap Mark schema (inline formatting)
export const proseMarkSchema = z.object({
    type: z.string().min(1),
    attrs: z.record(z.string(), z.any()).optional(),
});

// Type definitions for recursive schema
type ProseNodeType = {
    type: string;
    attrs?: Record<string, unknown>;
    content?: ProseNodeType[];
    text?: string;
    marks?: { type: string; attrs?: Record<string, unknown> }[];
};

// ProseMirror/Tiptap Node schema (recursive)
export const proseNodeSchema: z.ZodType<ProseNodeType> = z.object({
    type: z.string().min(1),
    attrs: z.record(z.string(), z.any()).optional(),
    content: z.lazy(() => z.array(proseNodeSchema)).optional(),
    text: z.string().optional(),
    marks: z.array(proseMarkSchema).optional(),
}) as z.ZodType<ProseNodeType>;

// ProseMirror/Tiptap Document schema (root)
export const proseDocumentSchema = z.object({
    type: z.literal("doc"),
    content: z.array(proseNodeSchema),
});

// Type exports
export type ProjectBrief = z.infer<typeof projectBriefSchema>;
export type NarrativeArc = z.infer<typeof narrativeArcSchema>;
export type NarrativeArcList = z.infer<typeof narrativeArcListSchema>;
export type Outline = z.infer<typeof outlineSchema>;
export type OutlineList = z.infer<typeof outlineListSchema>;
export type Synopsis = z.infer<typeof synopsisSchema>;
export type StoryBible = z.infer<typeof storyBibleSchema>;
export type ProseMark = z.infer<typeof proseMarkSchema>;
export type ProseNode = ProseNodeType;
export type ProseDocument = z.infer<typeof proseDocumentSchema>;