/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects/new'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardProjectsProjectIdStoryboardRouteImport } from './routes/dashboard/projects/$projectId/storyboard'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard/projects/$projectId/settings'
import { Route as DashboardProjectsProjectIdScriptRouteImport } from './routes/dashboard/projects/$projectId/script'
import { Route as DashboardProjectsProjectIdOutlineRouteImport } from './routes/dashboard/projects/$projectId/outline'
import { Route as DashboardProjectsProjectIdElementsRouteImport } from './routes/dashboard/projects/$projectId/elements'
import { Route as DashboardProjectsProjectIdCharactersRouteImport } from './routes/dashboard/projects/$projectId/characters'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdStoryboardRoute =
  DashboardProjectsProjectIdStoryboardRouteImport.update({
    id: '/storyboard',
    path: '/storyboard',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdScriptRoute =
  DashboardProjectsProjectIdScriptRouteImport.update({
    id: '/script',
    path: '/script',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdOutlineRoute =
  DashboardProjectsProjectIdOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdElementsRoute =
  DashboardProjectsProjectIdElementsRouteImport.update({
    id: '/elements',
    path: '/elements',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdCharactersRoute =
  DashboardProjectsProjectIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/characters': typeof DashboardProjectsProjectIdCharactersRoute
  '/dashboard/projects/$projectId/elements': typeof DashboardProjectsProjectIdElementsRoute
  '/dashboard/projects/$projectId/outline': typeof DashboardProjectsProjectIdOutlineRoute
  '/dashboard/projects/$projectId/script': typeof DashboardProjectsProjectIdScriptRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/storyboard': typeof DashboardProjectsProjectIdStoryboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/characters': typeof DashboardProjectsProjectIdCharactersRoute
  '/dashboard/projects/$projectId/elements': typeof DashboardProjectsProjectIdElementsRoute
  '/dashboard/projects/$projectId/outline': typeof DashboardProjectsProjectIdOutlineRoute
  '/dashboard/projects/$projectId/script': typeof DashboardProjectsProjectIdScriptRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/storyboard': typeof DashboardProjectsProjectIdStoryboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/characters': typeof DashboardProjectsProjectIdCharactersRoute
  '/dashboard/projects/$projectId/elements': typeof DashboardProjectsProjectIdElementsRoute
  '/dashboard/projects/$projectId/outline': typeof DashboardProjectsProjectIdOutlineRoute
  '/dashboard/projects/$projectId/script': typeof DashboardProjectsProjectIdScriptRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/storyboard': typeof DashboardProjectsProjectIdStoryboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/projects'
    | '/dashboard/projects/$projectId/characters'
    | '/dashboard/projects/$projectId/elements'
    | '/dashboard/projects/$projectId/outline'
    | '/dashboard/projects/$projectId/script'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/storyboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/projects'
    | '/dashboard/projects/$projectId/characters'
    | '/dashboard/projects/$projectId/elements'
    | '/dashboard/projects/$projectId/outline'
    | '/dashboard/projects/$projectId/script'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/storyboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/projects/'
    | '/dashboard/projects/$projectId/characters'
    | '/dashboard/projects/$projectId/elements'
    | '/dashboard/projects/$projectId/outline'
    | '/dashboard/projects/$projectId/script'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/storyboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId/storyboard': {
      id: '/dashboard/projects/$projectId/storyboard'
      path: '/storyboard'
      fullPath: '/dashboard/projects/$projectId/storyboard'
      preLoaderRoute: typeof DashboardProjectsProjectIdStoryboardRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/script': {
      id: '/dashboard/projects/$projectId/script'
      path: '/script'
      fullPath: '/dashboard/projects/$projectId/script'
      preLoaderRoute: typeof DashboardProjectsProjectIdScriptRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/outline': {
      id: '/dashboard/projects/$projectId/outline'
      path: '/outline'
      fullPath: '/dashboard/projects/$projectId/outline'
      preLoaderRoute: typeof DashboardProjectsProjectIdOutlineRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/elements': {
      id: '/dashboard/projects/$projectId/elements'
      path: '/elements'
      fullPath: '/dashboard/projects/$projectId/elements'
      preLoaderRoute: typeof DashboardProjectsProjectIdElementsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/characters': {
      id: '/dashboard/projects/$projectId/characters'
      path: '/characters'
      fullPath: '/dashboard/projects/$projectId/characters'
      preLoaderRoute: typeof DashboardProjectsProjectIdCharactersRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdCharactersRoute: typeof DashboardProjectsProjectIdCharactersRoute
  DashboardProjectsProjectIdElementsRoute: typeof DashboardProjectsProjectIdElementsRoute
  DashboardProjectsProjectIdOutlineRoute: typeof DashboardProjectsProjectIdOutlineRoute
  DashboardProjectsProjectIdScriptRoute: typeof DashboardProjectsProjectIdScriptRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdStoryboardRoute: typeof DashboardProjectsProjectIdStoryboardRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdCharactersRoute:
      DashboardProjectsProjectIdCharactersRoute,
    DashboardProjectsProjectIdElementsRoute:
      DashboardProjectsProjectIdElementsRoute,
    DashboardProjectsProjectIdOutlineRoute:
      DashboardProjectsProjectIdOutlineRoute,
    DashboardProjectsProjectIdScriptRoute:
      DashboardProjectsProjectIdScriptRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdStoryboardRoute:
      DashboardProjectsProjectIdStoryboardRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
