/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardMainRouteImport } from './routes/dashboard/main'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminParametersRouteImport } from './routes/admin/parameters'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminContentCategoriesRouteImport } from './routes/admin/content-categories'
import { Route as AdminCommandsRouteImport } from './routes/admin/commands'
import { Route as AdminParametersIndexRouteImport } from './routes/admin/parameters/index'
import { Route as AdminModelsIndexRouteImport } from './routes/admin/models/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects/new'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardMainProjectsRouteImport } from './routes/dashboard/main/projects'
import { Route as AdminParametersParameterIdRouteImport } from './routes/admin/parameters/$parameterId'
import { Route as AdminModelsModelIdRouteImport } from './routes/admin/models/$modelId'
import { Route as AdminCategoriesModelsRouteImport } from './routes/admin/categories/models'
import { Route as AdminCategoriesContentRouteImport } from './routes/admin/categories/content'
import { Route as DashboardProjectsProjectIdGenerateRouteImport } from './routes/dashboard/projects/$projectId/generate'
import { Route as DashboardProjectsProjectIdEditorRouteImport } from './routes/dashboard/projects/$projectId/editor'
import { Route as DashboardProjectsProjectIdEditRouteImport } from './routes/dashboard/projects/$projectId/edit'
import { Route as DashboardProjectsProjectIdVideoEditorIndexRouteImport } from './routes/dashboard/projects/$projectId/video-editor/index'
import { Route as DashboardProjectsProjectIdSkillMarketIndexRouteImport } from './routes/dashboard/projects/$projectId/skill-market/index'
import { Route as DashboardProjectsProjectIdVideoEditorFileNodeIdRouteImport } from './routes/dashboard/projects/$projectId/video-editor/$fileNodeId'
import { Route as DashboardProjectsProjectIdSkillMarketSkillIdRouteImport } from './routes/dashboard/projects/$projectId/skill-market/$skillId'
import { Route as DashboardProjectsProjectIdEditStoryboardRouteImport } from './routes/dashboard/projects/$projectId/edit/storyboard'
import { Route as DashboardProjectsProjectIdEditSettingsRouteImport } from './routes/dashboard/projects/$projectId/edit/settings'
import { Route as DashboardProjectsProjectIdEditScriptRouteImport } from './routes/dashboard/projects/$projectId/edit/script'
import { Route as DashboardProjectsProjectIdEditElementsRouteImport } from './routes/dashboard/projects/$projectId/edit/elements'
import { Route as DashboardProjectsProjectIdEditCharactersRouteImport } from './routes/dashboard/projects/$projectId/edit/characters'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardMainRoute = DashboardMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametersRoute = AdminParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentCategoriesRoute = AdminContentCategoriesRouteImport.update({
  id: '/content-categories',
  path: '/content-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandsRoute = AdminCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametersIndexRoute = AdminParametersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminParametersRoute,
} as any)
const AdminModelsIndexRoute = AdminModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModelsRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMainProjectsRoute = DashboardMainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardMainRoute,
} as any)
const AdminParametersParameterIdRoute =
  AdminParametersParameterIdRouteImport.update({
    id: '/$parameterId',
    path: '/$parameterId',
    getParentRoute: () => AdminParametersRoute,
  } as any)
const AdminModelsModelIdRoute = AdminModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => AdminModelsRoute,
} as any)
const AdminCategoriesModelsRoute = AdminCategoriesModelsRouteImport.update({
  id: '/categories/models',
  path: '/categories/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesContentRoute = AdminCategoriesContentRouteImport.update({
  id: '/categories/content',
  path: '/categories/content',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProjectsProjectIdGenerateRoute =
  DashboardProjectsProjectIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEditorRoute =
  DashboardProjectsProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEditRoute =
  DashboardProjectsProjectIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdVideoEditorIndexRoute =
  DashboardProjectsProjectIdVideoEditorIndexRouteImport.update({
    id: '/video-editor/',
    path: '/video-editor/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSkillMarketIndexRoute =
  DashboardProjectsProjectIdSkillMarketIndexRouteImport.update({
    id: '/skill-market/',
    path: '/skill-market/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdVideoEditorFileNodeIdRoute =
  DashboardProjectsProjectIdVideoEditorFileNodeIdRouteImport.update({
    id: '/video-editor/$fileNodeId',
    path: '/video-editor/$fileNodeId',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSkillMarketSkillIdRoute =
  DashboardProjectsProjectIdSkillMarketSkillIdRouteImport.update({
    id: '/skill-market/$skillId',
    path: '/skill-market/$skillId',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEditStoryboardRoute =
  DashboardProjectsProjectIdEditStoryboardRouteImport.update({
    id: '/storyboard',
    path: '/storyboard',
    getParentRoute: () => DashboardProjectsProjectIdEditRoute,
  } as any)
const DashboardProjectsProjectIdEditSettingsRoute =
  DashboardProjectsProjectIdEditSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdEditRoute,
  } as any)
const DashboardProjectsProjectIdEditScriptRoute =
  DashboardProjectsProjectIdEditScriptRouteImport.update({
    id: '/script',
    path: '/script',
    getParentRoute: () => DashboardProjectsProjectIdEditRoute,
  } as any)
const DashboardProjectsProjectIdEditElementsRoute =
  DashboardProjectsProjectIdEditElementsRouteImport.update({
    id: '/elements',
    path: '/elements',
    getParentRoute: () => DashboardProjectsProjectIdEditRoute,
  } as any)
const DashboardProjectsProjectIdEditCharactersRoute =
  DashboardProjectsProjectIdEditCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => DashboardProjectsProjectIdEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/content-categories': typeof AdminContentCategoriesRoute
  '/admin/models': typeof AdminModelsRouteWithChildren
  '/admin/parameters': typeof AdminParametersRouteWithChildren
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/dashboard/main': typeof DashboardMainRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/content': typeof AdminCategoriesContentRoute
  '/admin/categories/models': typeof AdminCategoriesModelsRoute
  '/admin/models/$modelId': typeof AdminModelsModelIdRoute
  '/admin/parameters/$parameterId': typeof AdminParametersParameterIdRoute
  '/dashboard/main/projects': typeof DashboardMainProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
  '/admin/parameters/': typeof AdminParametersIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRouteWithChildren
  '/dashboard/projects/$projectId/editor': typeof DashboardProjectsProjectIdEditorRoute
  '/dashboard/projects/$projectId/generate': typeof DashboardProjectsProjectIdGenerateRoute
  '/dashboard/projects/$projectId/edit/characters': typeof DashboardProjectsProjectIdEditCharactersRoute
  '/dashboard/projects/$projectId/edit/elements': typeof DashboardProjectsProjectIdEditElementsRoute
  '/dashboard/projects/$projectId/edit/script': typeof DashboardProjectsProjectIdEditScriptRoute
  '/dashboard/projects/$projectId/edit/settings': typeof DashboardProjectsProjectIdEditSettingsRoute
  '/dashboard/projects/$projectId/edit/storyboard': typeof DashboardProjectsProjectIdEditStoryboardRoute
  '/dashboard/projects/$projectId/skill-market/$skillId': typeof DashboardProjectsProjectIdSkillMarketSkillIdRoute
  '/dashboard/projects/$projectId/video-editor/$fileNodeId': typeof DashboardProjectsProjectIdVideoEditorFileNodeIdRoute
  '/dashboard/projects/$projectId/skill-market': typeof DashboardProjectsProjectIdSkillMarketIndexRoute
  '/dashboard/projects/$projectId/video-editor': typeof DashboardProjectsProjectIdVideoEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/content-categories': typeof AdminContentCategoriesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/dashboard/main': typeof DashboardMainRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/categories/content': typeof AdminCategoriesContentRoute
  '/admin/categories/models': typeof AdminCategoriesModelsRoute
  '/admin/models/$modelId': typeof AdminModelsModelIdRoute
  '/admin/parameters/$parameterId': typeof AdminParametersParameterIdRoute
  '/dashboard/main/projects': typeof DashboardMainProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/models': typeof AdminModelsIndexRoute
  '/admin/parameters': typeof AdminParametersIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRouteWithChildren
  '/dashboard/projects/$projectId/editor': typeof DashboardProjectsProjectIdEditorRoute
  '/dashboard/projects/$projectId/generate': typeof DashboardProjectsProjectIdGenerateRoute
  '/dashboard/projects/$projectId/edit/characters': typeof DashboardProjectsProjectIdEditCharactersRoute
  '/dashboard/projects/$projectId/edit/elements': typeof DashboardProjectsProjectIdEditElementsRoute
  '/dashboard/projects/$projectId/edit/script': typeof DashboardProjectsProjectIdEditScriptRoute
  '/dashboard/projects/$projectId/edit/settings': typeof DashboardProjectsProjectIdEditSettingsRoute
  '/dashboard/projects/$projectId/edit/storyboard': typeof DashboardProjectsProjectIdEditStoryboardRoute
  '/dashboard/projects/$projectId/skill-market/$skillId': typeof DashboardProjectsProjectIdSkillMarketSkillIdRoute
  '/dashboard/projects/$projectId/video-editor/$fileNodeId': typeof DashboardProjectsProjectIdVideoEditorFileNodeIdRoute
  '/dashboard/projects/$projectId/skill-market': typeof DashboardProjectsProjectIdSkillMarketIndexRoute
  '/dashboard/projects/$projectId/video-editor': typeof DashboardProjectsProjectIdVideoEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/admin/commands': typeof AdminCommandsRoute
  '/admin/content-categories': typeof AdminContentCategoriesRoute
  '/admin/models': typeof AdminModelsRouteWithChildren
  '/admin/parameters': typeof AdminParametersRouteWithChildren
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/dashboard/main': typeof DashboardMainRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/content': typeof AdminCategoriesContentRoute
  '/admin/categories/models': typeof AdminCategoriesModelsRoute
  '/admin/models/$modelId': typeof AdminModelsModelIdRoute
  '/admin/parameters/$parameterId': typeof AdminParametersParameterIdRoute
  '/dashboard/main/projects': typeof DashboardMainProjectsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
  '/admin/parameters/': typeof AdminParametersIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRouteWithChildren
  '/dashboard/projects/$projectId/editor': typeof DashboardProjectsProjectIdEditorRoute
  '/dashboard/projects/$projectId/generate': typeof DashboardProjectsProjectIdGenerateRoute
  '/dashboard/projects/$projectId/edit/characters': typeof DashboardProjectsProjectIdEditCharactersRoute
  '/dashboard/projects/$projectId/edit/elements': typeof DashboardProjectsProjectIdEditElementsRoute
  '/dashboard/projects/$projectId/edit/script': typeof DashboardProjectsProjectIdEditScriptRoute
  '/dashboard/projects/$projectId/edit/settings': typeof DashboardProjectsProjectIdEditSettingsRoute
  '/dashboard/projects/$projectId/edit/storyboard': typeof DashboardProjectsProjectIdEditStoryboardRoute
  '/dashboard/projects/$projectId/skill-market/$skillId': typeof DashboardProjectsProjectIdSkillMarketSkillIdRoute
  '/dashboard/projects/$projectId/video-editor/$fileNodeId': typeof DashboardProjectsProjectIdVideoEditorFileNodeIdRoute
  '/dashboard/projects/$projectId/skill-market/': typeof DashboardProjectsProjectIdSkillMarketIndexRoute
  '/dashboard/projects/$projectId/video-editor/': typeof DashboardProjectsProjectIdVideoEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-error'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/admin/commands'
    | '/admin/content-categories'
    | '/admin/models'
    | '/admin/parameters'
    | '/admin/skills'
    | '/admin/vendors'
    | '/dashboard/main'
    | '/admin/'
    | '/dashboard/'
    | '/admin/categories/content'
    | '/admin/categories/models'
    | '/admin/models/$modelId'
    | '/admin/parameters/$parameterId'
    | '/dashboard/main/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/admin/categories'
    | '/admin/models/'
    | '/admin/parameters/'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/editor'
    | '/dashboard/projects/$projectId/generate'
    | '/dashboard/projects/$projectId/edit/characters'
    | '/dashboard/projects/$projectId/edit/elements'
    | '/dashboard/projects/$projectId/edit/script'
    | '/dashboard/projects/$projectId/edit/settings'
    | '/dashboard/projects/$projectId/edit/storyboard'
    | '/dashboard/projects/$projectId/skill-market/$skillId'
    | '/dashboard/projects/$projectId/video-editor/$fileNodeId'
    | '/dashboard/projects/$projectId/skill-market'
    | '/dashboard/projects/$projectId/video-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/admin/commands'
    | '/admin/content-categories'
    | '/admin/skills'
    | '/admin/vendors'
    | '/dashboard/main'
    | '/admin'
    | '/dashboard'
    | '/admin/categories/content'
    | '/admin/categories/models'
    | '/admin/models/$modelId'
    | '/admin/parameters/$parameterId'
    | '/dashboard/main/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/admin/categories'
    | '/admin/models'
    | '/admin/parameters'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/editor'
    | '/dashboard/projects/$projectId/generate'
    | '/dashboard/projects/$projectId/edit/characters'
    | '/dashboard/projects/$projectId/edit/elements'
    | '/dashboard/projects/$projectId/edit/script'
    | '/dashboard/projects/$projectId/edit/settings'
    | '/dashboard/projects/$projectId/edit/storyboard'
    | '/dashboard/projects/$projectId/skill-market/$skillId'
    | '/dashboard/projects/$projectId/video-editor/$fileNodeId'
    | '/dashboard/projects/$projectId/skill-market'
    | '/dashboard/projects/$projectId/video-editor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth-error'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/admin/commands'
    | '/admin/content-categories'
    | '/admin/models'
    | '/admin/parameters'
    | '/admin/skills'
    | '/admin/vendors'
    | '/dashboard/main'
    | '/admin/'
    | '/dashboard/'
    | '/admin/categories/content'
    | '/admin/categories/models'
    | '/admin/models/$modelId'
    | '/admin/parameters/$parameterId'
    | '/dashboard/main/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/admin/categories/'
    | '/admin/models/'
    | '/admin/parameters/'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/editor'
    | '/dashboard/projects/$projectId/generate'
    | '/dashboard/projects/$projectId/edit/characters'
    | '/dashboard/projects/$projectId/edit/elements'
    | '/dashboard/projects/$projectId/edit/script'
    | '/dashboard/projects/$projectId/edit/settings'
    | '/dashboard/projects/$projectId/edit/storyboard'
    | '/dashboard/projects/$projectId/skill-market/$skillId'
    | '/dashboard/projects/$projectId/video-editor/$fileNodeId'
    | '/dashboard/projects/$projectId/skill-market/'
    | '/dashboard/projects/$projectId/video-editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/main': {
      id: '/dashboard/main'
      path: '/main'
      fullPath: '/dashboard/main'
      preLoaderRoute: typeof DashboardMainRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parameters': {
      id: '/admin/parameters'
      path: '/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AdminParametersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-categories': {
      id: '/admin/content-categories'
      path: '/content-categories'
      fullPath: '/admin/content-categories'
      preLoaderRoute: typeof AdminContentCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commands': {
      id: '/admin/commands'
      path: '/commands'
      fullPath: '/admin/commands'
      preLoaderRoute: typeof AdminCommandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parameters/': {
      id: '/admin/parameters/'
      path: '/'
      fullPath: '/admin/parameters/'
      preLoaderRoute: typeof AdminParametersIndexRouteImport
      parentRoute: typeof AdminParametersRoute
    }
    '/admin/models/': {
      id: '/admin/models/'
      path: '/'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AdminModelsIndexRouteImport
      parentRoute: typeof AdminModelsRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/main/projects': {
      id: '/dashboard/main/projects'
      path: '/projects'
      fullPath: '/dashboard/main/projects'
      preLoaderRoute: typeof DashboardMainProjectsRouteImport
      parentRoute: typeof DashboardMainRoute
    }
    '/admin/parameters/$parameterId': {
      id: '/admin/parameters/$parameterId'
      path: '/$parameterId'
      fullPath: '/admin/parameters/$parameterId'
      preLoaderRoute: typeof AdminParametersParameterIdRouteImport
      parentRoute: typeof AdminParametersRoute
    }
    '/admin/models/$modelId': {
      id: '/admin/models/$modelId'
      path: '/$modelId'
      fullPath: '/admin/models/$modelId'
      preLoaderRoute: typeof AdminModelsModelIdRouteImport
      parentRoute: typeof AdminModelsRoute
    }
    '/admin/categories/models': {
      id: '/admin/categories/models'
      path: '/categories/models'
      fullPath: '/admin/categories/models'
      preLoaderRoute: typeof AdminCategoriesModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/content': {
      id: '/admin/categories/content'
      path: '/categories/content'
      fullPath: '/admin/categories/content'
      preLoaderRoute: typeof AdminCategoriesContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/projects/$projectId/generate': {
      id: '/dashboard/projects/$projectId/generate'
      path: '/generate'
      fullPath: '/dashboard/projects/$projectId/generate'
      preLoaderRoute: typeof DashboardProjectsProjectIdGenerateRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/editor': {
      id: '/dashboard/projects/$projectId/editor'
      path: '/editor'
      fullPath: '/dashboard/projects/$projectId/editor'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditorRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/edit': {
      id: '/dashboard/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectId/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/video-editor/': {
      id: '/dashboard/projects/$projectId/video-editor/'
      path: '/video-editor'
      fullPath: '/dashboard/projects/$projectId/video-editor'
      preLoaderRoute: typeof DashboardProjectsProjectIdVideoEditorIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/skill-market/': {
      id: '/dashboard/projects/$projectId/skill-market/'
      path: '/skill-market'
      fullPath: '/dashboard/projects/$projectId/skill-market'
      preLoaderRoute: typeof DashboardProjectsProjectIdSkillMarketIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/video-editor/$fileNodeId': {
      id: '/dashboard/projects/$projectId/video-editor/$fileNodeId'
      path: '/video-editor/$fileNodeId'
      fullPath: '/dashboard/projects/$projectId/video-editor/$fileNodeId'
      preLoaderRoute: typeof DashboardProjectsProjectIdVideoEditorFileNodeIdRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/skill-market/$skillId': {
      id: '/dashboard/projects/$projectId/skill-market/$skillId'
      path: '/skill-market/$skillId'
      fullPath: '/dashboard/projects/$projectId/skill-market/$skillId'
      preLoaderRoute: typeof DashboardProjectsProjectIdSkillMarketSkillIdRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/edit/storyboard': {
      id: '/dashboard/projects/$projectId/edit/storyboard'
      path: '/storyboard'
      fullPath: '/dashboard/projects/$projectId/edit/storyboard'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditStoryboardRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEditRoute
    }
    '/dashboard/projects/$projectId/edit/settings': {
      id: '/dashboard/projects/$projectId/edit/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/edit/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEditRoute
    }
    '/dashboard/projects/$projectId/edit/script': {
      id: '/dashboard/projects/$projectId/edit/script'
      path: '/script'
      fullPath: '/dashboard/projects/$projectId/edit/script'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditScriptRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEditRoute
    }
    '/dashboard/projects/$projectId/edit/elements': {
      id: '/dashboard/projects/$projectId/edit/elements'
      path: '/elements'
      fullPath: '/dashboard/projects/$projectId/edit/elements'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditElementsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEditRoute
    }
    '/dashboard/projects/$projectId/edit/characters': {
      id: '/dashboard/projects/$projectId/edit/characters'
      path: '/characters'
      fullPath: '/dashboard/projects/$projectId/edit/characters'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditCharactersRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEditRoute
    }
  }
}

interface AdminModelsRouteChildren {
  AdminModelsModelIdRoute: typeof AdminModelsModelIdRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
}

const AdminModelsRouteChildren: AdminModelsRouteChildren = {
  AdminModelsModelIdRoute: AdminModelsModelIdRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
}

const AdminModelsRouteWithChildren = AdminModelsRoute._addFileChildren(
  AdminModelsRouteChildren,
)

interface AdminParametersRouteChildren {
  AdminParametersParameterIdRoute: typeof AdminParametersParameterIdRoute
  AdminParametersIndexRoute: typeof AdminParametersIndexRoute
}

const AdminParametersRouteChildren: AdminParametersRouteChildren = {
  AdminParametersParameterIdRoute: AdminParametersParameterIdRoute,
  AdminParametersIndexRoute: AdminParametersIndexRoute,
}

const AdminParametersRouteWithChildren = AdminParametersRoute._addFileChildren(
  AdminParametersRouteChildren,
)

interface AdminRouteChildren {
  AdminCommandsRoute: typeof AdminCommandsRoute
  AdminContentCategoriesRoute: typeof AdminContentCategoriesRoute
  AdminModelsRoute: typeof AdminModelsRouteWithChildren
  AdminParametersRoute: typeof AdminParametersRouteWithChildren
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesContentRoute: typeof AdminCategoriesContentRoute
  AdminCategoriesModelsRoute: typeof AdminCategoriesModelsRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommandsRoute: AdminCommandsRoute,
  AdminContentCategoriesRoute: AdminContentCategoriesRoute,
  AdminModelsRoute: AdminModelsRouteWithChildren,
  AdminParametersRoute: AdminParametersRouteWithChildren,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesContentRoute: AdminCategoriesContentRoute,
  AdminCategoriesModelsRoute: AdminCategoriesModelsRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardMainRouteChildren {
  DashboardMainProjectsRoute: typeof DashboardMainProjectsRoute
}

const DashboardMainRouteChildren: DashboardMainRouteChildren = {
  DashboardMainProjectsRoute: DashboardMainProjectsRoute,
}

const DashboardMainRouteWithChildren = DashboardMainRoute._addFileChildren(
  DashboardMainRouteChildren,
)

interface DashboardProjectsProjectIdEditRouteChildren {
  DashboardProjectsProjectIdEditCharactersRoute: typeof DashboardProjectsProjectIdEditCharactersRoute
  DashboardProjectsProjectIdEditElementsRoute: typeof DashboardProjectsProjectIdEditElementsRoute
  DashboardProjectsProjectIdEditScriptRoute: typeof DashboardProjectsProjectIdEditScriptRoute
  DashboardProjectsProjectIdEditSettingsRoute: typeof DashboardProjectsProjectIdEditSettingsRoute
  DashboardProjectsProjectIdEditStoryboardRoute: typeof DashboardProjectsProjectIdEditStoryboardRoute
}

const DashboardProjectsProjectIdEditRouteChildren: DashboardProjectsProjectIdEditRouteChildren =
  {
    DashboardProjectsProjectIdEditCharactersRoute:
      DashboardProjectsProjectIdEditCharactersRoute,
    DashboardProjectsProjectIdEditElementsRoute:
      DashboardProjectsProjectIdEditElementsRoute,
    DashboardProjectsProjectIdEditScriptRoute:
      DashboardProjectsProjectIdEditScriptRoute,
    DashboardProjectsProjectIdEditSettingsRoute:
      DashboardProjectsProjectIdEditSettingsRoute,
    DashboardProjectsProjectIdEditStoryboardRoute:
      DashboardProjectsProjectIdEditStoryboardRoute,
  }

const DashboardProjectsProjectIdEditRouteWithChildren =
  DashboardProjectsProjectIdEditRoute._addFileChildren(
    DashboardProjectsProjectIdEditRouteChildren,
  )

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdEditRoute: typeof DashboardProjectsProjectIdEditRouteWithChildren
  DashboardProjectsProjectIdEditorRoute: typeof DashboardProjectsProjectIdEditorRoute
  DashboardProjectsProjectIdGenerateRoute: typeof DashboardProjectsProjectIdGenerateRoute
  DashboardProjectsProjectIdSkillMarketSkillIdRoute: typeof DashboardProjectsProjectIdSkillMarketSkillIdRoute
  DashboardProjectsProjectIdVideoEditorFileNodeIdRoute: typeof DashboardProjectsProjectIdVideoEditorFileNodeIdRoute
  DashboardProjectsProjectIdSkillMarketIndexRoute: typeof DashboardProjectsProjectIdSkillMarketIndexRoute
  DashboardProjectsProjectIdVideoEditorIndexRoute: typeof DashboardProjectsProjectIdVideoEditorIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdEditRoute:
      DashboardProjectsProjectIdEditRouteWithChildren,
    DashboardProjectsProjectIdEditorRoute:
      DashboardProjectsProjectIdEditorRoute,
    DashboardProjectsProjectIdGenerateRoute:
      DashboardProjectsProjectIdGenerateRoute,
    DashboardProjectsProjectIdSkillMarketSkillIdRoute:
      DashboardProjectsProjectIdSkillMarketSkillIdRoute,
    DashboardProjectsProjectIdVideoEditorFileNodeIdRoute:
      DashboardProjectsProjectIdVideoEditorFileNodeIdRoute,
    DashboardProjectsProjectIdSkillMarketIndexRoute:
      DashboardProjectsProjectIdSkillMarketIndexRoute,
    DashboardProjectsProjectIdVideoEditorIndexRoute:
      DashboardProjectsProjectIdVideoEditorIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardMainRoute: typeof DashboardMainRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMainRoute: DashboardMainRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
