/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdStoryboardRouteImport } from './routes/projects/$projectId/storyboard'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdScriptRouteImport } from './routes/projects/$projectId/script'
import { Route as ProjectsProjectIdOutlineRouteImport } from './routes/projects/$projectId/outline'
import { Route as ProjectsProjectIdElementsRouteImport } from './routes/projects/$projectId/elements'
import { Route as ProjectsProjectIdCharactersRouteImport } from './routes/projects/$projectId/characters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdStoryboardRoute =
  ProjectsProjectIdStoryboardRouteImport.update({
    id: '/projects/$projectId/storyboard',
    path: '/projects/$projectId/storyboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdScriptRoute = ProjectsProjectIdScriptRouteImport.update({
  id: '/projects/$projectId/script',
  path: '/projects/$projectId/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdOutlineRoute =
  ProjectsProjectIdOutlineRouteImport.update({
    id: '/projects/$projectId/outline',
    path: '/projects/$projectId/outline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdElementsRoute =
  ProjectsProjectIdElementsRouteImport.update({
    id: '/projects/$projectId/elements',
    path: '/projects/$projectId/elements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdCharactersRoute =
  ProjectsProjectIdCharactersRouteImport.update({
    id: '/projects/$projectId/characters',
    path: '/projects/$projectId/characters',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/elements': typeof ProjectsProjectIdElementsRoute
  '/projects/$projectId/outline': typeof ProjectsProjectIdOutlineRoute
  '/projects/$projectId/script': typeof ProjectsProjectIdScriptRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/storyboard': typeof ProjectsProjectIdStoryboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/elements': typeof ProjectsProjectIdElementsRoute
  '/projects/$projectId/outline': typeof ProjectsProjectIdOutlineRoute
  '/projects/$projectId/script': typeof ProjectsProjectIdScriptRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/storyboard': typeof ProjectsProjectIdStoryboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/elements': typeof ProjectsProjectIdElementsRoute
  '/projects/$projectId/outline': typeof ProjectsProjectIdOutlineRoute
  '/projects/$projectId/script': typeof ProjectsProjectIdScriptRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/storyboard': typeof ProjectsProjectIdStoryboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/elements'
    | '/projects/$projectId/outline'
    | '/projects/$projectId/script'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/storyboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/elements'
    | '/projects/$projectId/outline'
    | '/projects/$projectId/script'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/storyboard'
  id:
    | '__root__'
    | '/'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/elements'
    | '/projects/$projectId/outline'
    | '/projects/$projectId/script'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/storyboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdCharactersRoute: typeof ProjectsProjectIdCharactersRoute
  ProjectsProjectIdElementsRoute: typeof ProjectsProjectIdElementsRoute
  ProjectsProjectIdOutlineRoute: typeof ProjectsProjectIdOutlineRoute
  ProjectsProjectIdScriptRoute: typeof ProjectsProjectIdScriptRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdStoryboardRoute: typeof ProjectsProjectIdStoryboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/storyboard': {
      id: '/projects/$projectId/storyboard'
      path: '/projects/$projectId/storyboard'
      fullPath: '/projects/$projectId/storyboard'
      preLoaderRoute: typeof ProjectsProjectIdStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/script': {
      id: '/projects/$projectId/script'
      path: '/projects/$projectId/script'
      fullPath: '/projects/$projectId/script'
      preLoaderRoute: typeof ProjectsProjectIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/outline': {
      id: '/projects/$projectId/outline'
      path: '/projects/$projectId/outline'
      fullPath: '/projects/$projectId/outline'
      preLoaderRoute: typeof ProjectsProjectIdOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/elements': {
      id: '/projects/$projectId/elements'
      path: '/projects/$projectId/elements'
      fullPath: '/projects/$projectId/elements'
      preLoaderRoute: typeof ProjectsProjectIdElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/characters': {
      id: '/projects/$projectId/characters'
      path: '/projects/$projectId/characters'
      fullPath: '/projects/$projectId/characters'
      preLoaderRoute: typeof ProjectsProjectIdCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdCharactersRoute: ProjectsProjectIdCharactersRoute,
  ProjectsProjectIdElementsRoute: ProjectsProjectIdElementsRoute,
  ProjectsProjectIdOutlineRoute: ProjectsProjectIdOutlineRoute,
  ProjectsProjectIdScriptRoute: ProjectsProjectIdScriptRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdStoryboardRoute: ProjectsProjectIdStoryboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
