/**
 * Bindings for this Worker.
 *
 * `Env` is generated by `pnpm cf-typegen` (`wrangler types`) from
 * `wrangler.jsonc`. Secrets are not part of the Wrangler config, so they are
 * declared here:
 *
 *   RENDER_SERVICE_TOKEN — shared bearer token the Sohizi API presents on
 *   every render route. Set with `wrangler secret put RENDER_SERVICE_TOKEN`.
 */
export type WorkerEnv = Env & {
  RENDER_SERVICE_TOKEN?: string
}

export function readIntVar(
  value: string | undefined,
  fallback: number,
  { min, max }: { min: number; max: number },
): number {
  const parsed = Number(value)
  if (!Number.isFinite(parsed)) return fallback
  return Math.min(max, Math.max(min, Math.trunc(parsed)))
}
