import { MediaChatList } from './media-chat-list'
import { MediaChatInput } from './media-chat-input'
import { Sheet, SheetHeader, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet'
import { useMediaGeneratorStore } from '../store/media-generator-store'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

export default function MediaChat({ projectId }: { projectId: string }) {
  return (
    <>
    <div className='flex flex-col h-full'>
        <MediaChatList projectId={projectId}/>
        <MediaChatInput projectId={projectId} 
                        className='mx-2 mb-2'
        />
    </div>
    <ViewSheet />
    </>
  )
}

const ViewSheet = () => {
  const viewRequestInput = useMediaGeneratorStore((state) => state.viewRequestInput)
  const setViewRequestInput = useMediaGeneratorStore((state) => state.setViewRequestInput)

  const jobs = viewRequestInput?.jobs || []
  const description = `Here ${jobs.length > 1 ? 'are' : 'is'} the optimized ${jobs.length > 1 ? 'requests' : 'request'} generated by the AI for the media generation.`

  return (
    <Sheet open={!!viewRequestInput} onOpenChange={() => setViewRequestInput(null)}>
      <SheetContent className='md:max-w-2xl'>
        <SheetHeader>
          <SheetTitle>AI generated requests</SheetTitle>
          <SheetDescription>{description}</SheetDescription>
        </SheetHeader>
        <div className='flex flex-col gap-6 overflow-y-auto p-4'>
          {
            jobs.map((job, index) => (
              <RenderJob key={index} job={job} />
            ))
          }
        </div>
      </SheetContent>
    </Sheet>
  )
}

const RenderJob = ({job}: {job: Record<string, string>}) => {
  const entries = Object.entries(job)
  return (
    <div className="**:data-[slot=table-container]:overflow-visible border rounded-xl overflow-hidden">
    <Table className="">
      <TableHeader className="bg-muted">
        <TableRow>
          <TableHead>Key</TableHead>
          <TableHead>Value</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {
          entries.map(([key, value]) => (
            <TableRow key={key} className='text-muted-foreground'>
              <TableCell className="whitespace-normal">{key}</TableCell>
              <TableCell className="whitespace-normal break-all">
                {typeof value === "string" ? value : JSON.stringify(value)}
              </TableCell>
            </TableRow>
          ))
        }
      </TableBody>
    </Table>
    </div>

  )
}